//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WowDotNetAPI.Explorers.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WowDotNetAPI.Explorers.Test.TestStrings", typeof(TestStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        /// </summary>
        internal static string APIKey {
            get {
                return ResourceManager.GetString("APIKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;battlegroups&quot;: [{
        ///        &quot;name&quot;: &quot;Bloodlust&quot;,
        ///        &quot;slug&quot;: &quot;bloodlust&quot;
        ///    }, {
        ///        &quot;name&quot;: &quot;Coliseum 1&quot;,
        ///        &quot;slug&quot;: &quot;coliseum-1&quot;
        ///    }, {
        ///        &quot;name&quot;: &quot;Cyclone&quot;,
        ///        &quot;slug&quot;: &quot;cyclone&quot;
        ///    }, {
        ///        &quot;name&quot;: &quot;Emberstorm&quot;,
        ///        &quot;slug&quot;: &quot;emberstorm&quot;
        ///    }, {
        ///        &quot;name&quot;: &quot;Nightfall&quot;,
        ///        &quot;slug&quot;: &quot;nightfall&quot;
        ///    }, {
        ///        &quot;name&quot;: &quot;Rampage&quot;,
        ///        &quot;slug&quot;: &quot;rampage&quot;
        ///    }, {
        ///        &quot;name&quot;: &quot;Reckoning&quot;,
        ///        &quot;slug&quot;: &quot;reckoning&quot;
        ///    }, {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestBattleGroups {
            get {
                return ResourceManager.GetString("TestBattleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;achievementPoints&quot;:6895,&quot;achievements&quot;:{&quot;achievementsCompleted&quot;:[6,7,8,9,10,11,12,13,31,32,33,35,38,39,44,45,73,116,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,137,141,153,154,159,165,166,168,199,201,204,208,218,220,223,227,229,231,233,238,239,245,246,255,283,288,292,295,397,398,402,403,406,429,431,432,435,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,503,504,505,506,507,508,509,512,513,515,516,518,519,520,521,522,523,524,545,546,547,556,55 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestCharacter {
            get {
                return ResourceManager.GetString("TestCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;realms&quot;:[{&quot;name&quot;:&quot;Aegwynn&quot;,&quot;population&quot;:&quot;low&quot;,&quot;queue&quot;:false,&quot;slug&quot;:&quot;aegwynn&quot;,&quot;status&quot;:true,&quot;type&quot;:&quot;pvp&quot;},{&quot;name&quot;:&quot;Aerie Peak&quot;,&quot;population&quot;:&quot;medium&quot;,&quot;queue&quot;:false,&quot;slug&quot;:&quot;aerie-peak&quot;,&quot;status&quot;:true,&quot;type&quot;:&quot;pve&quot;},{&quot;name&quot;:&quot;Agamaggan&quot;,&quot;population&quot;:&quot;low&quot;,&quot;queue&quot;:false,&quot;slug&quot;:&quot;agamaggan&quot;,&quot;status&quot;:true,&quot;type&quot;:&quot;pvp&quot;},{&quot;name&quot;:&quot;Aggramar&quot;,&quot;population&quot;:&quot;medium&quot;,&quot;queue&quot;:false,&quot;slug&quot;:&quot;aggramar&quot;,&quot;status&quot;:true,&quot;type&quot;:&quot;pve&quot;},{&quot;name&quot;:&quot;Akama&quot;,&quot;population&quot;:&quot;medium&quot;,&quot;queue&quot;:false,&quot;slug&quot;:&quot;akama&quot;,&quot;status&quot;:true,&quot;type&quot;:&quot;pvp&quot;},{&q....
        /// </summary>
        internal static string TestRealms {
            get {
                return ResourceManager.GetString("TestRealms", resourceCulture);
            }
        }
    }
}
